[package]
name = "chroniker"
version = "0.3.0"
description="A simple library to help with time"
license="MIT"
keywords = ["time"]
authors = ["DevOrc <ncharlton002@gmail.com>"]
repository="https://github.com/DevOrc/chroniker"

[dependencies]
