[package]
name = "chroniker"
version = "0.3.1"
description="A simple library to help with time"
license="MIT"
keywords = ["time"]
authors = ["DevOrc <ncharlton002@gmail.com>"]
documentation="https://docs.rs/crate/chroniker"
repository="https://github.com/DevOrc/chroniker"

[dependencies]
